// quiz-app-vue/src/components/Question.vue
<template>
    <div class="card p-4">
      <h4>{{ question.question }}</h4>
  
      <div v-if="question.type === 'multiple-choice'" class="mt-3">
        <button
          v-for="(option, index) in question.options"
          :key="index"
          class="btn btn-outline-primary m-2"
          :class="{ active: userAnswer === option }"
          @click="selectAnswer(option)"
        >
          {{ option }}
        </button>
      </div>
  
      <div v-else class="mt-3">
        <button
          class="btn btn-outline-success m-2"
          :class="{ active: userAnswer === true }"
          @click="selectAnswer(true)"
        >
          True
        </button>
        <button
          class="btn btn-outline-danger m-2"
          :class="{ active: userAnswer === false }"
          @click="selectAnswer(false)"
        >
          False
        </button>
      </div>
    </div>
  </template>
  
  <script>
  export default {
    props: {
      question: Object,
      userAnswer: [String, Boolean]
    },
    methods: {
      selectAnswer(answer) {
        this.$emit('answered', answer);
      }
    }
  };
  </script>

// quiz-app-react/src/Question.js
import React from "react";

function Question({ question, onAnswer, userAnswer }) {
  const handleOptionClick = (option) => {
    onAnswer(option);
  };

  const handleTrueFalseClick = (value) => {
    onAnswer(value);
  };

  return (
    <div className="card p-4">
      <h4>{question.question}</h4>

      {question.type === "multiple-choice" ? (
        <div className="mt-3">
          {question.options.map((option, index) => (
            <button
              key={index}
              className={`btn btn-outline-primary m-2 ${
                userAnswer === option ? "active" : ""
              }`}
              onClick={() => handleOptionClick(option)}
            >
              {option}
            </button>
          ))}
        </div>
      ) : (
        <div className="mt-3">
          <button
            className={`btn btn-outline-success m-2 ${
              userAnswer === true ? "active" : ""
            }`}
            onClick={() => handleTrueFalseClick(true)}
          >
            True
          </button>
          <button
            className={`btn btn-outline-danger m-2 ${
              userAnswer === false ? "active" : ""
            }`}
            onClick={() => handleTrueFalseClick(false)}
          >
            False
          </button>
        </div>
      )}
    </div>
  );
}

export default Question;
